//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Luxury.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoTinhTrang
    {
        public int ID_BaoCao { get; set; }
        public string Ma_Phong { get; set; }
        public Nullable<int> ID_Trang_Thai { get; set; }
        public Nullable<System.DateTime> NgayGhiNhan { get; set; }
        public string GhiChu { get; set; }
    
        public virtual Trang_Thai Trang_Thai { get; set; }
        public virtual Room Room { get; set; }
    }
}
