//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Luxury.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int ID_ChiTiet { get; set; }
        public Nullable<int> ID_ThanhToan { get; set; }
        public string LoaiChiPhi { get; set; }
        public string ID_DichVu { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual DichVuPhuThu DichVuPhuThu { get; set; }
        public virtual ThanhToan ThanhToan { get; set; }
    }
}
