//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Luxury.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Luxury_HotelEntities : DbContext
    {
        public Luxury_HotelEntities()
            : base("name=Luxury_HotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoCaoTinhTrang> BaoCaoTinhTrangs { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DbSet<DanhGia> DanhGias { get; set; }
        public virtual DbSet<DichVuPhuThu> DichVuPhuThus { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<ThanhToan> ThanhToans { get; set; }
        public virtual DbSet<TienIch> TienIches { get; set; }
        public virtual DbSet<Trang_Thai> Trang_Thai { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<YeuCauDichVu> YeuCauDichVus { get; set; }
    }
}
