//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Luxury.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public string ID_DanhGia { get; set; }
        public string BookingID { get; set; }
        public Nullable<int> DiemDanhGia { get; set; }
        public string NoiDungDanhGia { get; set; }
        public Nullable<System.DateTime> NgayDanhGia { get; set; }
        public string AnhMinhHoa { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
