//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Luxury.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVuPhuThu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DichVuPhuThu()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.YeuCauDichVus = new HashSet<YeuCauDichVu>();
        }
    
        public string ID_DichVu { get; set; }
        public string Ten_DichVu { get; set; }
        public Nullable<decimal> Gia_DichVu { get; set; }
        public Nullable<System.TimeSpan> ThoiGianMo { get; set; }
        public Nullable<System.TimeSpan> ThoiGianKetThuc { get; set; }
        public Nullable<int> ID_Trang_Thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual Trang_Thai Trang_Thai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuCauDichVu> YeuCauDichVus { get; set; }
    }
}
