//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Luxury.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong_TienIch
    {
        public string Ma_Phong { get; set; }
        public int ID_TienIch { get; set; }
        public Nullable<System.DateTime> Ngay_Them_Tien_Ich_Phong { get; set; }
    
        public virtual TienIch TienIch { get; set; }
        public virtual Room Room { get; set; }
    }
}
