//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Luxury.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.BaoCaoTinhTrangs = new HashSet<BaoCaoTinhTrang>();
            this.Bookings = new HashSet<Booking>();
            this.Phong_TienIch = new HashSet<Phong_TienIch>();
        }
    
        public string Ma_Phong { get; set; }
        public string Ten_Phong { get; set; }
        public string Mo_Ta { get; set; }
        public decimal Gia_Phong { get; set; }
        public string Dia_Diem { get; set; }
        public Nullable<int> So_Nguoi { get; set; }
        public string Anh_Phong { get; set; }
        public Nullable<int> ID_Trang_Thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaoCaoTinhTrang> BaoCaoTinhTrangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong_TienIch> Phong_TienIch { get; set; }
        public virtual Trang_Thai Trang_Thai { get; set; }
    }
}
