//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM_Luxury.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauDichVu
    {
        public int ID_YeuCau { get; set; }
        public string BookingID { get; set; }
        public string ID_DichVu { get; set; }
        public Nullable<System.DateTime> ThoiGianYeuCau { get; set; }
        public Nullable<int> ID_Trang_Thai { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual DichVuPhuThu DichVuPhuThu { get; set; }
        public virtual Trang_Thai Trang_Thai { get; set; }
    }
}
